[package]
name = "afm_gui"
version = "0.1.0"
edition = "2024"

[dependencies]
afm_core = { path = "../afm_core" }
slint = "1.9"
hex = "0.4"
rfd = { version = "0.15", default-features = false, features = ["xdg-portal", "async-std"] }
arboard = "3"
log = "0.4"

[build-dependencies]
slint-build = "1.9"
